.\" Manpage for moncd.
.TH MONCD 1 "30 juin 2024" "SE" "monshell - Commandes internes"
.SH NAME
moncd \- changer de répertoire courant
.SH SYNOPSIS
moncd [repertoire]
.SH DESCRIPTION
La commande moncd permet de changer le répertoire courant de l'environnement d'exécution du shell. Si le paramètre répertoire cible n'est pas spécifié, la valeur de la variable d'environnement HOME est utilisée par défaut. 
.SH OPTIONS
La commande moncd n'accepte pas d'options.
.SH NOTES
NB : le caractère '~' (pour désigner le répertoire $HOME) n'est pas pris en charge. 
.SH SEE ALSO
monexit(1)
.SH BUGS
No known bugs.