.\" Manpage for monexit.
.TH MONEXIT 1 "30 juin 2024" "SE" "monshell - Commandes internes"
.SH NAME
monexit \- quitter le shell normalement
.SH SYNOPSIS
monexit
.SH DESCRIPTION
La commande monexit permet de fermer le shell (terminaison du processus).
.SH OPTIONS
La commande monexit n'accepte pas d'options.
.SH NOTES
Cette commande équivaut à l'envoi d'un caractère EOF sur une ligne vide ; le même résultat peut être obtenu à l'aide du raccourci CTRL + D. 
.SH SEE ALSO
moncd(1)
.SH BUGS
No known bugs.